# Generated by Django 4.1.4 on 2023-07-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Name',
            new_name='name',
        ),
    ]
